[tools]
eza = "latest"
fd = "latest"
fzf = "latest"
rg = "latest"
neovim = "0.12.1"
bat = "latest"
node = "22"
uv = "latest"
go = "latest"
gh = "latest"
lazygit = "latest"
delta = "latest"
ffmpeg = "latest"
"npm:@dokobot/cli" = "latest"
"npm:cubox-cli" = "latest"
"npm:oh-my-opencode" = "latest"
bun = "latest"
"npm:agent-browser" = "latest"
zoxide = "latest"
carapace = "latest"
atuin = "latest"
