
[[plugins]]
repo = 'vim-python/python-syntax'
on_ft = 'python'
hook_source = '''
	let g:python_highlight_all = 1
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'vim-scripts/python_match.vim'
on_ft = 'python'

[[plugins]]
repo = 'raimon49/requirements.txt.vim'
on_ft = 'requirements'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'
hook_source = '''
    let g:html5_event_handler_attributes_complete = 0
    let g:html5_rdfa_attributes_complete = 0
    let g:html5_microdata_attributes_complete = 0
    let g:html5_aria_attributes_complete = 0
'''

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = [ 'javascript', 'javascriptreact' ]
hook_source = '''
	let g:javascript_plugin_jsdoc = 1
    let g:javascript_plugin_flow = 1
'''

[[plugins]]
repo = 'moll/vim-node'
on_ft = [ 'javascript', 'javascriptreact' ]

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = [ 'typescript', 'typescriptreact' ]

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'hardcoreplayers/go-nvim'
on_ft = ['go','gomod']
hook_add = '''
	nnoremap gcg :GoAuToComment<CR>
'''
hook_source = '''
	call coc#config('languageserver', {
	\ 'golang': {
		\ "command": "gopls",
		\ "rootPatterns": ["go.mod"],
		\ "disableWorkspaceFolders": "true",
		\ "filetypes": ["go"]
		\ }
		\})
'''

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'
on_ft = [ 'scss', 'sass' ]

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = [ 'javascript', 'javascriptreact', 'typescriptreact' ]
depends = 'vim-javascript'
hook_add = '''
	let g:vim_jsx_pretty_colorful_config = 1
'''

[[plugins]]
repo = 'arzg/vim-sh'
on_ft = [ 'sh','zsh' ]
hook_source = '''
	call coc#config('languageserver', {
	\ 'bash': {
		\ "command": "bash-language-server",
		\ "args" : ["start"],
		\ "ignoredRootPaths": ["~"],
		\ "filetypes": ["sh"]
		\ }
		\})
'''

[[plugins]]
repo = 'groenewege/vim-less'
on_ft = 'less'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'
