search_mode = "fuzzy"
filter_mode = "workspace"
workspaces = true

style = "compact"
inline_height = 18
inline_height_shell_up_key_binding = 18
invert = true
show_preview = true
max_preview_height = 4
show_help = false
show_tabs = false

enter_accept = true
secrets_filter = true
update_check = false

[theme]
name = "marine"

[search]
filters = ["workspace", "directory", "session", "global"]

[preview]
strategy = "auto"

[ui]
columns = ["duration", "time", { type = "directory", width = 24 }, "command"]
