#!/bin/zsh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# only load apps that need to be managed
yabai -m rule --add app=".+" manage=off
yabai -m rule --add app=".+" mouse_follows_focus=off
apps=$(awk -v ORS='|' '{if($0!="") print $0}' $yabai_config_path/yabaimanaged)
yabai -m rule --add app="^${apps%?}$" manage=on
yabai -m rule --add app="^${apps%?}$" mouse_follows_focus=on

# event signal listen
yabai -m signal --add event=window_minimized action="yabai -m window --focus recent"
# yabai -m signal --add event=window_destroyed action="yabai -m window --focus recent"

# ====== global configure ======
# https://github.com/koekeishiya/yabai/wiki/Configuration

# enable tiled layout
window_padding=10
yabai -m config layout         bsp
yabai -m config window_gap     ${window_padding}
yabai -m config top_padding    ${window_padding}
yabai -m config left_padding   ${window_padding}
yabai -m config right_padding  ${window_padding}
yabai -m config bottom_padding ${window_padding}
# on or off (default: off)
yabai -m config auto_balance off
# Floating point value between 0 and 1 (default: 0.5)
yabai -m config split_ratio 0.5
# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn
# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# set focus follows mouse mode (default: off, options: off, autoraise, autofocus)
yabai -m config focus_follows_mouse autoraise
# set mouse follows focus mode (default: off)
yabai -m config mouse_follows_focus on
# action performed when a bsp-managed window is dropped in the center of some other bsp-managed window (options: swap, stack)
yabai -m config mouse_drop_action stack
# floating windows are always on top (default: off)
yabai -m config window_topmost off
# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float
# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9
# external_bar location:top_padding:bottom_padding
# for every space located on the main display
# yabai -m config external_bar main:0:25
# for all spaces regardless of the display it belongs to
brew services start spacebar
SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:0:$SPACEBAR_HEIGHT

